version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: transmission_server_1
      APP_PORT: 9091

  server:
    image: ddsderek/transmission:latest
    environment:
      - PUID=1000
      - PGID=1000
      - USER=altan
      - PASS=beta12
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    ports:
      - 51413:51413
#     - 9091:9091
      - 51413:51413/udp
    restart: unless-stopped

  widget-server:
    image: getumbrel/umbrel-transmission-widget-server:v1.0.0@sha256:0ee30f1eecbf6f4f3f62e3f6d5c1626bd31d15ace7e97cacff5fc091836650cf
    environment:
      - TRANSMISSION_URL=http://transmission_server_1
      - TRANSMISSION_PORT=9091
    restart: on-failure
